"""empty message

Revision ID: b681fb908d41
Revises: 47c625f91b55
Create Date: 2019-03-21 23:11:38.026042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b681fb908d41'
down_revision = '47c625f91b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'name')
    # ### end Alembic commands ###
