# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_person2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first'),
        ),
        migrations.AlterField(
            model_name='person2',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='lastname'),
        ),
    ]
